namespace Aspose.Slides.Foss.Internal;

/// <summary>
/// Bidirectional mapping between OOXML preset geometry strings and <see cref="ShapeType"/> enum values.
/// </summary>
internal static class OoxmlPresetMapping
{
    private static readonly Dictionary<string, ShapeType> PrstToShapeType = new(StringComparer.Ordinal)
    {
        ["line"] = ShapeType.Line,
        ["lineInv"] = ShapeType.LineInverse,
        ["triangle"] = ShapeType.Triangle,
        ["rtTriangle"] = ShapeType.RightTriangle,
        ["rect"] = ShapeType.Rectangle,
        ["diamond"] = ShapeType.Diamond,
        ["parallelogram"] = ShapeType.Parallelogram,
        ["trapezoid"] = ShapeType.Trapezoid,
        ["nonIsoscelesTrapezoid"] = ShapeType.NonIsoscelesTrapezoid,
        ["pentagon"] = ShapeType.Pentagon,
        ["hexagon"] = ShapeType.Hexagon,
        ["heptagon"] = ShapeType.Heptagon,
        ["octagon"] = ShapeType.Octagon,
        ["decagon"] = ShapeType.Decagon,
        ["dodecagon"] = ShapeType.Dodecagon,
        ["star4"] = ShapeType.FourPointedStar,
        ["star5"] = ShapeType.FivePointedStar,
        ["star6"] = ShapeType.SixPointedStar,
        ["star7"] = ShapeType.SevenPointedStar,
        ["star8"] = ShapeType.EightPointedStar,
        ["star10"] = ShapeType.TenPointedStar,
        ["star12"] = ShapeType.TwelvePointedStar,
        ["star16"] = ShapeType.SixteenPointedStar,
        ["star24"] = ShapeType.TwentyFourPointedStar,
        ["star32"] = ShapeType.ThirtyTwoPointedStar,
        ["roundRect"] = ShapeType.RoundCornerRectangle,
        ["round1Rect"] = ShapeType.OneRoundCornerRectangle,
        ["round2SameRect"] = ShapeType.TwoSamesideRoundCornerRectangle,
        ["round2DiagRect"] = ShapeType.TwoDiagonalRoundCornerRectangle,
        ["snipRoundRect"] = ShapeType.OneSnipOneRoundCornerRectangle,
        ["snip1Rect"] = ShapeType.OneSnipCornerRectangle,
        ["snip2SameRect"] = ShapeType.TwoSamesideSnipCornerRectangle,
        ["snip2DiagRect"] = ShapeType.TwoDiagonalSnipCornerRectangle,
        ["plaque"] = ShapeType.Plaque,
        ["ellipse"] = ShapeType.Ellipse,
        ["teardrop"] = ShapeType.Teardrop,
        ["homePlate"] = ShapeType.HomePlate,
        ["chevron"] = ShapeType.Chevron,
        ["pieWedge"] = ShapeType.PieWedge,
        ["pie"] = ShapeType.Pie,
        ["blockArc"] = ShapeType.BlockArc,
        ["donut"] = ShapeType.Donut,
        ["noSmoking"] = ShapeType.NoSmoking,
        ["rightArrow"] = ShapeType.RightArrow,
        ["leftArrow"] = ShapeType.LeftArrow,
        ["upArrow"] = ShapeType.UpArrow,
        ["downArrow"] = ShapeType.DownArrow,
        ["stripedRightArrow"] = ShapeType.StripedRightArrow,
        ["notchedRightArrow"] = ShapeType.NotchedRightArrow,
        ["bentUpArrow"] = ShapeType.BentUpArrow,
        ["leftRightArrow"] = ShapeType.LeftRightArrow,
        ["upDownArrow"] = ShapeType.UpDownArrow,
        ["leftUpArrow"] = ShapeType.LeftUpArrow,
        ["leftRightUpArrow"] = ShapeType.LeftRightUpArrow,
        ["quadArrow"] = ShapeType.QuadArrow,
        ["leftArrowCallout"] = ShapeType.CalloutLeftArrow,
        ["rightArrowCallout"] = ShapeType.CalloutRightArrow,
        ["upArrowCallout"] = ShapeType.CalloutUpArrow,
        ["downArrowCallout"] = ShapeType.CalloutDownArrow,
        ["leftRightArrowCallout"] = ShapeType.CalloutLeftRightArrow,
        ["upDownArrowCallout"] = ShapeType.CalloutUpDownArrow,
        ["quadArrowCallout"] = ShapeType.CalloutQuadArrow,
        ["bentArrow"] = ShapeType.BentArrow,
        ["uturnArrow"] = ShapeType.UTurnArrow,
        ["circularArrow"] = ShapeType.CircularArrow,
        ["leftCircularArrow"] = ShapeType.LeftCircularArrow,
        ["leftRightCircularArrow"] = ShapeType.LeftRightCircularArrow,
        ["curvedRightArrow"] = ShapeType.CurvedRightArrow,
        ["curvedLeftArrow"] = ShapeType.CurvedLeftArrow,
        ["curvedUpArrow"] = ShapeType.CurvedUpArrow,
        ["curvedDownArrow"] = ShapeType.CurvedDownArrow,
        ["swooshArrow"] = ShapeType.SwooshArrow,
        ["cube"] = ShapeType.Cube,
        ["can"] = ShapeType.Can,
        ["lightningBolt"] = ShapeType.LightningBolt,
        ["heart"] = ShapeType.Heart,
        ["sun"] = ShapeType.Sun,
        ["moon"] = ShapeType.Moon,
        ["smileyFace"] = ShapeType.SmileyFace,
        ["irregularSeal1"] = ShapeType.IrregularSeal1,
        ["irregularSeal2"] = ShapeType.IrregularSeal2,
        ["foldedCorner"] = ShapeType.FoldedCorner,
        ["bevel"] = ShapeType.Bevel,
        ["frame"] = ShapeType.Frame,
        ["halfFrame"] = ShapeType.HalfFrame,
        ["corner"] = ShapeType.Corner,
        ["diagStripe"] = ShapeType.DiagonalStripe,
        ["chord"] = ShapeType.Chord,
        ["arc"] = ShapeType.CurvedArc,
        ["leftBracket"] = ShapeType.LeftBracket,
        ["rightBracket"] = ShapeType.RightBracket,
        ["leftBrace"] = ShapeType.LeftBrace,
        ["rightBrace"] = ShapeType.RightBrace,
        ["bracketPair"] = ShapeType.BracketPair,
        ["bracePair"] = ShapeType.BracePair,
        ["straightConnector1"] = ShapeType.StraightConnector1,
        ["bentConnector2"] = ShapeType.BentConnector2,
        ["bentConnector3"] = ShapeType.BentConnector3,
        ["bentConnector4"] = ShapeType.BentConnector4,
        ["bentConnector5"] = ShapeType.BentConnector5,
        ["curvedConnector2"] = ShapeType.CurvedConnector2,
        ["curvedConnector3"] = ShapeType.CurvedConnector3,
        ["curvedConnector4"] = ShapeType.CurvedConnector4,
        ["curvedConnector5"] = ShapeType.CurvedConnector5,
        ["callout1"] = ShapeType.Callout1,
        ["callout2"] = ShapeType.Callout2,
        ["callout3"] = ShapeType.Callout3,
        ["accentCallout1"] = ShapeType.Callout1WithAccent,
        ["accentCallout2"] = ShapeType.Callout2WithAccent,
        ["accentCallout3"] = ShapeType.Callout3WithAccent,
        ["borderCallout1"] = ShapeType.Callout1WithBorder,
        ["borderCallout2"] = ShapeType.Callout2WithBorder,
        ["borderCallout3"] = ShapeType.Callout3WithBorder,
        ["accentBorderCallout1"] = ShapeType.Callout1WithBorderAndAccent,
        ["accentBorderCallout2"] = ShapeType.Callout2WithBorderAndAccent,
        ["accentBorderCallout3"] = ShapeType.Callout3WithBorderAndAccent,
        ["wedgeRectCallout"] = ShapeType.CalloutWedgeRectangle,
        ["wedgeRoundRectCallout"] = ShapeType.CalloutWedgeRoundRectangle,
        ["wedgeEllipseCallout"] = ShapeType.CalloutWedgeEllipse,
        ["cloudCallout"] = ShapeType.CalloutCloud,
        ["cloud"] = ShapeType.Cloud,
        ["ribbon"] = ShapeType.Ribbon,
        ["ribbon2"] = ShapeType.Ribbon2,
        ["ellipseRibbon"] = ShapeType.EllipseRibbon,
        ["ellipseRibbon2"] = ShapeType.EllipseRibbon2,
        ["leftRightRibbon"] = ShapeType.LeftRightRibbon,
        ["verticalScroll"] = ShapeType.VerticalScroll,
        ["horizontalScroll"] = ShapeType.HorizontalScroll,
        ["wave"] = ShapeType.Wave,
        ["doubleWave"] = ShapeType.DoubleWave,
        ["plus"] = ShapeType.Plus,
        ["flowChartProcess"] = ShapeType.ProcessFlow,
        ["flowChartDecision"] = ShapeType.DecisionFlow,
        ["flowChartInputOutput"] = ShapeType.InputOutputFlow,
        ["flowChartPredefinedProcess"] = ShapeType.PredefinedProcessFlow,
        ["flowChartInternalStorage"] = ShapeType.InternalStorageFlow,
        ["flowChartDocument"] = ShapeType.DocumentFlow,
        ["flowChartMultidocument"] = ShapeType.MultiDocumentFlow,
        ["flowChartTerminator"] = ShapeType.TerminatorFlow,
        ["flowChartPreparation"] = ShapeType.PreparationFlow,
        ["flowChartManualInput"] = ShapeType.ManualInputFlow,
        ["flowChartManualOperation"] = ShapeType.ManualOperationFlow,
        ["flowChartConnector"] = ShapeType.ConnectorFlow,
        ["flowChartPunchedCard"] = ShapeType.PunchedCardFlow,
        ["flowChartPunchedTape"] = ShapeType.PunchedTapeFlow,
        ["flowChartSummingJunction"] = ShapeType.SummingJunctionFlow,
        ["flowChartOr"] = ShapeType.OrFlow,
        ["flowChartCollate"] = ShapeType.CollateFlow,
        ["flowChartSort"] = ShapeType.SortFlow,
        ["flowChartExtract"] = ShapeType.ExtractFlow,
        ["flowChartMerge"] = ShapeType.MergeFlow,
        ["flowChartOfflineStorage"] = ShapeType.OfflineStorageFlow,
        ["flowChartOnlineStorage"] = ShapeType.OnlineStorageFlow,
        ["flowChartMagneticTape"] = ShapeType.MagneticTapeFlow,
        ["flowChartMagneticDisk"] = ShapeType.MagneticDiskFlow,
        ["flowChartMagneticDrum"] = ShapeType.MagneticDrumFlow,
        ["flowChartDisplay"] = ShapeType.DisplayFlow,
        ["flowChartDelay"] = ShapeType.DelayFlow,
        ["flowChartAlternateProcess"] = ShapeType.AlternateProcessFlow,
        ["flowChartOffpageConnector"] = ShapeType.OffPageConnectorFlow,
        ["actionButtonBlank"] = ShapeType.BlankButton,
        ["actionButtonHome"] = ShapeType.HomeButton,
        ["actionButtonHelp"] = ShapeType.HelpButton,
        ["actionButtonInformation"] = ShapeType.InformationButton,
        ["actionButtonForwardNext"] = ShapeType.ForwardOrNextButton,
        ["actionButtonBackPrevious"] = ShapeType.BackOrPreviousButton,
        ["actionButtonEnd"] = ShapeType.EndButton,
        ["actionButtonBeginning"] = ShapeType.BeginningButton,
        ["actionButtonReturn"] = ShapeType.ReturnButton,
        ["actionButtonDocument"] = ShapeType.DocumentButton,
        ["actionButtonSound"] = ShapeType.SoundButton,
        ["actionButtonMovie"] = ShapeType.MovieButton,
        ["gear6"] = ShapeType.Gear6,
        ["gear9"] = ShapeType.Gear9,
        ["funnel"] = ShapeType.Funnel,
        ["mathPlus"] = ShapeType.PlusMath,
        ["mathMinus"] = ShapeType.MinusMath,
        ["mathMultiply"] = ShapeType.MultiplyMath,
        ["mathDivide"] = ShapeType.DivideMath,
        ["mathEqual"] = ShapeType.EqualMath,
        ["mathNotEqual"] = ShapeType.NotEqualMath,
        ["cornerTabs"] = ShapeType.CornerTabs,
        ["squareTabs"] = ShapeType.SquareTabs,
        ["plaqueTabs"] = ShapeType.PlaqueTabs,
        ["chartX"] = ShapeType.ChartX,
        ["chartStar"] = ShapeType.ChartStar,
        ["chartPlus"] = ShapeType.ChartPlus,
    };

    private static readonly Dictionary<ShapeType, string> ShapeTypeToPrst;

    static OoxmlPresetMapping()
    {
        ShapeTypeToPrst = new Dictionary<ShapeType, string>(PrstToShapeType.Count);
        foreach (var kvp in PrstToShapeType)
        {
            ShapeTypeToPrst.TryAdd(kvp.Value, kvp.Key);
        }
    }

    /// <summary>
    /// Maps an OOXML preset string to a <see cref="ShapeType"/> value.
    /// Returns <see cref="ShapeType.NotDefined"/> if the string is not recognized.
    /// </summary>
    internal static ShapeType FromPreset(string? preset)
    {
        if (preset is null)
            return ShapeType.NotDefined;
        return PrstToShapeType.TryGetValue(preset, out var result) ? result : ShapeType.NotDefined;
    }

    /// <summary>
    /// Maps a <see cref="ShapeType"/> to the OOXML preset string.
    /// Returns <c>null</c> if no mapping exists (e.g. for <see cref="ShapeType.NotDefined"/> or <see cref="ShapeType.Custom"/>).
    /// </summary>
    internal static string? ToPreset(ShapeType shapeType)
    {
        return ShapeTypeToPrst.TryGetValue(shapeType, out var result) ? result : null;
    }
}
